# Nome do workflow
name: DevOpsLab

# Eventos que vão disparar o workflow
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.11
      
      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Run tests
        run: python -m unittest -v test