# Nome do workflow
name: DevOpsLab

# Eventos que vão disparar o workflow
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.11
      
      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Run tests
        run: python -m unittest -v test
  
  deploy-to-heroku:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      # Authenticate
      - name: Heroku login
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
    
      # Adicionando
      - name: Add Heroku Remote
        run: |
          heroku git:remote --app $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
    
      # Enviando
      - name: Deploy to Heroku
        run: |
          git push heroku HEAD:main --force
